#### Importing Libraries

In [7]:
import requests
import pandas as pd

#### Defining the function to fetch data

I used OpenAQ API to get the data. <br>
OpenAQ is the largest open-source air quality data platform, aggregating and harmonizing historical and real-time air quality data from diverse sources from across the globe.<br>
Learn more about OpenAQ : https://openaq.org/about/

In [8]:
def get_air_quality(country):
    url = f"https://api.openaq.org/v2/latest?country={country}"
    response = requests.get(url, headers={"X-API-Key": "f4006f414137ee1addf0a1aebf5f18926642a2a3ad8fc74347b54d48486d564f"})
    data = response.json()

    if response.status_code == 200:
        return data
    else:
        return None

In [9]:
country = "CN"  
air_quality_data = get_air_quality(country)

In [10]:
# Create a dataframe from the 'results' field in the dictionary
df = pd.json_normalize(air_quality_data['results'])
#Vizualise the dataframe
df

,location,city,country,measurements,coordinates.latitude,coordinates.longitude
0,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930
1,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280
2,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130
3,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080
4,Tai Po,New Territories,CN,"[{'parameter': 'pm25', 'value': 7.5, 'lastUpda...",22.450833,114.164444
...,...,...,...,...,...,...
95,哈啤分公司,None,CN,"[{'parameter': 'co', 'value': 400.0, 'lastUpda...",47.341600,130.253700
96,哈密师范学校,None,CN,"[{'parameter': 'pm25', 'value': 17.0, 'lastUpd...",42.832800,93.496100
97,哈达湾,None,CN,"[{'parameter': 'co', 'value': 900.0, 'lastUpda...",43.862200,126.540000
98,哈达街,None,CN,"[{'parameter': 'no2', 'value': 44.0, 'lastUpda...",42.272800,118.957600
99,唐家,None,CN,"[{'parameter': 'pm25', 'value': 5.0, 'lastUpda...",22.425100,113.628000

In [11]:
df['measurements']

0     [{'parameter': 'pressure', 'value': 980.81, 'l...
1     [{'parameter': 'pm10', 'value': 14.7, 'lastUpd...
2     [{'parameter': 'humidity', 'value': 57.0, 'las...
3     [{'parameter': 'um010', 'value': 1.3, 'lastUpd...
4     [{'parameter': 'pm25', 'value': 7.5, 'lastUpda...
                            ...
95    [{'parameter': 'co', 'value': 400.0, 'lastUpda...
96    [{'parameter': 'pm25', 'value': 17.0, 'lastUpd...
97    [{'parameter': 'co', 'value': 900.0, 'lastUpda...
98    [{'parameter': 'no2', 'value': 44.0, 'lastUpda...
99    [{'parameter': 'pm25', 'value': 5.0, 'lastUpda...
Name: measurements, Length: 100, dtype: object

The column measurments contains a dictionnary of measurments we need to analyse, so we have to unpack this dictionnary.

In [12]:
# Let's unpack the dictionaries
expanded_data = []
for i, row in df.iterrows():
    expanded_row = pd.json_normalize(row['measurements'])
    expanded_row['index'] = i  # Keep track of the original row
    expanded_data.append(expanded_row)

# Concatenate all the expanded data
expanded_df = pd.concat(expanded_data)

# Now, you can merge this expanded data back to your original DataFrame
df = df.merge(expanded_df, left_index=True, right_on='index')

In [14]:
df.head(60)

,location,city,country,measurements,coordinates.latitude,coordinates.longitude,parameter,value,lastUpdated,unit,index
0,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,pressure,980.81,2023-08-15T10:47:25+00:00,mb,0
1,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,um003,7.76,2023-08-15T10:47:25+00:00,particles/cm³,0
2,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,humidity,73.00,2023-08-15T10:47:25+00:00,%,0
3,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,temperature,80.00,2023-08-15T10:47:25+00:00,f,0
4,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,um010,0.41,2023-08-15T10:47:25+00:00,particles/cm³,0
5,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,um005,2.16,2023-08-15T10:47:25+00:00,particles/cm³,0
6,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,pm1,3.30,2023-08-15T10:47:25+00:00,µg/m³,0
7,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,um025,0.03,2023-08-15T10:47:25+00:00,particles/cm³,0
8,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,pm10,5.70,2023-08-15T10:47:25+00:00,µg/m³,0
9,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,um050,0.00,2023-08-15T10:47:25+00:00,particles/cm³,0
10,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,pm25,5.40,2023-08-15T10:47:25+00:00,µg/m³,0
11,TVA Connected Communities #3,None,CN,"[{'parameter': 'pressure', 'value': 980.81, 'l...",35.991707,-83.892930,um100,0.00,2023-08-15T10:47:25+00:00,particles/cm³,0
0,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,pm10,14.70,2023-08-15T10:49:06+00:00,µg/m³,1
1,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,pressure,1000.65,2023-08-15T10:49:06+00:00,mb,1
2,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,um003,21.59,2023-08-15T10:49:06+00:00,particles/cm³,1
3,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,humidity,52.00,2023-08-15T10:49:06+00:00,%,1
4,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,um050,0.01,2023-08-15T10:49:06+00:00,particles/cm³,1
5,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,um010,0.65,2023-08-15T10:49:06+00:00,particles/cm³,1
6,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,um005,5.89,2023-08-15T10:49:06+00:00,particles/cm³,1
7,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,um100,0.00,2023-08-15T10:49:06+00:00,particles/cm³,1
8,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,um025,0.03,2023-08-15T10:49:06+00:00,particles/cm³,1
9,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,temperature,100.00,2023-08-15T10:49:06+00:00,f,1
10,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,pm1,10.70,2023-08-15T10:49:06+00:00,µg/m³,1
11,Science Park Shenzhen,None,CN,"[{'parameter': 'pm10', 'value': 14.7, 'lastUpd...",22.528564,113.943280,pm25,13.70,2023-08-15T10:49:06+00:00,µg/m³,1
0,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,humidity,57.00,2023-08-15T10:48:43+00:00,%,2
1,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,um010,2.43,2023-08-15T10:48:43+00:00,particles/cm³,2
2,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,um003,31.88,2023-08-15T10:48:43+00:00,particles/cm³,2
3,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,pm1,18.40,2023-08-15T10:48:43+00:00,µg/m³,2
4,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,um025,0.11,2023-08-15T10:48:43+00:00,particles/cm³,2
5,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,um100,0.00,2023-08-15T10:48:43+00:00,particles/cm³,2
6,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,temperature,78.00,2023-08-15T10:48:43+00:00,f,2
7,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,pm25,30.40,2023-08-15T10:48:43+00:00,µg/m³,2
8,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,um005,9.44,2023-08-15T10:48:43+00:00,particles/cm³,2
9,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,um050,0.01,2023-08-15T10:48:43+00:00,particles/cm³,2
10,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,pm10,32.50,2023-08-15T10:48:43+00:00,µg/m³,2
11,Juarez casa,None,CN,"[{'parameter': 'humidity', 'value': 57.0, 'las...",33.717400,117.903130,pressure,1012.83,2023-08-15T10:48:43+00:00,mb,2
0,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,um010,1.30,2023-08-15T10:45:14+00:00,particles/cm³,3
1,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,pressure,1002.36,2023-08-15T10:45:14+00:00,mb,3
2,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,humidity,49.00,2023-08-15T10:45:14+00:00,%,3
3,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,um003,26.69,2023-08-15T10:45:14+00:00,particles/cm³,3
4,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,pm10,23.10,2023-08-15T10:45:14+00:00,µg/m³,3
5,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,um050,0.01,2023-08-15T10:45:14+00:00,particles/cm³,3
6,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,um005,7.48,2023-08-15T10:45:14+00:00,particles/cm³,3
7,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,um100,0.01,2023-08-15T10:45:14+00:00,particles/cm³,3
8,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,pm25,21.40,2023-08-15T10:45:14+00:00,µg/m³,3
9,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,um025,0.11,2023-08-15T10:45:14+00:00,particles/cm³,3
10,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,pm1,14.80,2023-08-15T10:45:14+00:00,µg/m³,3
11,"Kunshan, Suzhou, China",None,CN,"[{'parameter': 'um010', 'value': 1.3, 'lastUpd...",31.404840,120.904080,temperature,98.00,2023-08-15T10:45:14+00:00,f,3
0,Tai Po,New Territories,CN,"[{'parameter': 'pm25', 'value': 7.5, 'lastUpda...",22.450833,114.164444,pm25,7.50,2023-08-15T10:00:00+00:00,µg/m³,4
1,Tai Po,New Territories,CN,"[{'parameter': 'pm25', 'value': 7.5, 'lastUpda...",22.450833,114.164444,o3,33.80,2023-08-15T10:00:00+00:00,µg/m³,4
2,Tai Po,New Territories,CN,"[{'parameter': 'pm25', 'value': 7.5, 'lastUpda...",22.450833,114.164444,pm10,14.60,2023-08-15T10:00:00+00:00,µg/m³,4
3,Tai Po,New Territories,CN,"[{'parameter': 'pm25', 'value': 7.5, 'lastUpda...",22.450833,114.164444,so2,2.70,2023-08-15T10:00:00+00:00,µg/m³,4
4,Tai Po,New Territories,CN,"[{'parameter': 'pm25', 'value': 7.5, 'lastUpda...",22.450833,114.164444,no2,33.50,2023-08-15T10:00:00+00:00,µg/m³,4
0,Mong Kok,Kowloon,CN,"[{'parameter': 'pm10', 'value': 22.0, 'lastUpd...",22.322500,114.168333,pm10,22.00,2023-08-15T10:00:00+00:00,µg/m³,5
1,Mong Kok,Kowloon,CN,"[{'parameter': 'pm10', 'value': 22.0, 'lastUpd...",22.322500,114.168333,co,765.70,2023-08-15T10:00:00+00:00,µg/m³,5
2,Mong Kok,Kowloon,CN,"[{'parameter': 'pm10', 'value': 22.0, 'lastUpd...",22.322500,114.168333,so2,5.40,2023-08-15T10:00:00+00:00,µg/m³,5
3,Mong Kok,Kowloon,CN,"[{'parameter': 'pm10', 'value': 22.0, 'lastUpd...",22.322500,114.168333,pm25,13.00,2023-08-15T10:00:00+00:00,µg/m³,5
4,Mong Kok,Kowloon,CN,"[{'parameter': 'pm10', 'value': 22.0, 'lastUpd...",22.322500,114.168333,o3,19.60,2023-08-15T10:00:00+00:00,µg/m³,5
5,Mong Kok,Kowloon,CN,"[{'parameter': 'pm10', 'value': 22.0, 'lastUpd...",22.322500,114.168333,no2,65.40,2023-08-15T10:00:00+00:00,µg/m³,5
0,Yuen Long,New Territories,CN,"[{'parameter': 'pm25', 'value': 8.9, 'lastUpda...",22.445278,114.022778,pm25,8.90,2023-08-15T10:00:00+00:00,µg/m³,6

In [23]:
# Pivot the DataFrame
pivot_df = expanded_df.pivot(index='index', columns='parameter', values='value')

# Reset the index
pivot_df = pivot_df.reset_index()

# Join the pivoted data with original data
final_df = pd.merge(df.drop('measurements', axis=1), pivot_df, on='index')

# Drop the index column
final_df = final_df.drop(columns=['index'])

In [24]:
final_df

,location,city,country,coordinates.latitude,coordinates.longitude,parameter,value,lastUpdated,unit,co,...,pm25,pressure,so2,temperature,um003,um005,um010,um025,um050,um100
0,"Kunshan, Suzhou, China",None,CN,31.40484,120.90408,um010,1.34,2023-07-31T10:11:58+00:00,particles/cm³,NaN,...,18.5,1004.43,NaN,98.0,20.09,5.72,1.34,0.13,0.02,0.02
1,"Kunshan, Suzhou, China",None,CN,31.40484,120.90408,um003,20.09,2023-07-31T10:11:58+00:00,particles/cm³,NaN,...,18.5,1004.43,NaN,98.0,20.09,5.72,1.34,0.13,0.02,0.02
2,"Kunshan, Suzhou, China",None,CN,31.40484,120.90408,pm1,10.80,2023-07-31T10:11:58+00:00,µg/m³,NaN,...,18.5,1004.43,NaN,98.0,20.09,5.72,1.34,0.13,0.02,0.02
3,"Kunshan, Suzhou, China",None,CN,31.40484,120.90408,um025,0.13,2023-07-31T10:11:58+00:00,particles/cm³,NaN,...,18.5,1004.43,NaN,98.0,20.09,5.72,1.34,0.13,0.02,0.02
4,"Kunshan, Suzhou, China",None,CN,31.40484,120.90408,pm25,18.50,2023-07-31T10:11:58+00:00,µg/m³,NaN,...,18.5,1004.43,NaN,98.0,20.09,5.72,1.34,0.13,0.02,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,原169医院(对照点),None,CN,26.91670,112.50030,no2,9.00,2021-08-09T11:00:00+00:00,µg/m³,600.0,...,12.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
563,原169医院(对照点),None,CN,26.91670,112.50030,pm10,15.00,2021-08-09T11:00:00+00:00,µg/m³,600.0,...,12.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
564,原169医院(对照点),None,CN,26.91670,112.50030,so2,4.00,2021-08-09T11:00:00+00:00,µg/m³,600.0,...,12.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
565,原169医院(对照点),None,CN,26.91670,112.50030,o3,119.00,2021-08-09T11:00:00+00:00,µg/m³,600.0,...,12.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566,原169医院(对照点),None,CN,26.91670,112.50030,co,600.00,2021-08-09T11:00:00+00:00,µg/m³,600.0,...,12.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
sewi = final_df.drop_duplicates(subset='location')

In [26]:
sewi.shape

(97, 25)

In [27]:
sewi.columns

Index(['location', 'city', 'country', 'coordinates.latitude',
       'coordinates.longitude', 'parameter', 'value', 'lastUpdated', 'unit',
       'co', 'humidity', 'no2', 'o3', 'pm1', 'pm10', 'pm25', 'pressure', 'so2',
       'temperature', 'um003', 'um005', 'um010', 'um025', 'um050', 'um100'],
      dtype='object')

In [28]:
sewi.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 97 entries, 0 to 561
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   location               97 non-null     object
 1   city                   25 non-null     object
 2   country                97 non-null     object
 3   coordinates.latitude   97 non-null     float64
 4   coordinates.longitude  97 non-null     float64
 5   parameter              97 non-null     object
 6   value                  97 non-null     float64
 7   lastUpdated            97 non-null     object
 8   unit                   97 non-null     object
 9   co                     71 non-null     float64
 10  humidity               6 non-null      float64
 11  no2                    78 non-null     float64
 12  o3                     80 non-null     float64
 13  pm1                    9 non-null      float64
 14  pm10                   87 non-null     float64
 15  pm25                   96 non-null     float64
 16  pressure               6 non-null      float64
 17  so2                    79 non-null     float64
 18  temperature            6 non-null      float64
 19  um003                  6 non-null      float64
 20  um005                  6 non-null      float64
 21  um010                  9 non-null      float64
 22  um025                  9 non-null      float64
 23  um050                  6 non-null      float64
 24  um100                  9 non-null      float64
dtypes: float64(19), object(6)
memory usage: 19.7+ KB

In [29]:
sewi["city"].isnull().count()

97

##### Columns to delete
The "city" column contains just null values so we can delete it. <br>
The "country" column because we are dealing with a single country (China)  <br>
The "lastUpdated" column which contains just time variables. <br>
The "parameter" and "value" because now we have each paramter as a column.

In [30]:
sewi = sewi.drop(['city', 'country', 'lastUpdated', 'parameter', 'value'], axis=1)

In [31]:
sewi.head()

,location,coordinates.latitude,coordinates.longitude,unit,co,humidity,no2,o3,pm1,pm10,pm25,pressure,so2,temperature,um003,um005,um010,um025,um050,um100
0,"Kunshan, Suzhou, China",31.404840,120.90408,particles/cm³,NaN,55.0,NaN,NaN,10.8,20.4,18.5,1004.43,NaN,98.0,20.09,5.72,1.34,0.13,0.02,0.02
12,atelierYVF,22.290922,114.19941,mb,NaN,60.0,NaN,NaN,3.3,5.7,4.8,1001.94,NaN,93.0,11.94,2.54,0.33,0.03,0.01,0.00
24,TVA Connected Communities #3,35.991707,-83.89293,particles/cm³,NaN,69.0,NaN,NaN,7.1,10.2,9.8,983.91,NaN,75.0,13.27,3.70,0.62,0.03,0.00,0.00
36,Juarez casa,33.717400,117.90313,µg/m³,NaN,61.0,NaN,NaN,10.3,17.0,15.3,1010.70,NaN,79.0,18.49,5.34,1.08,0.06,0.02,0.01
48,Science Park Shenzhen,22.528564,113.94328,mb,NaN,57.0,NaN,NaN,6.7,7.6,7.5,999.63,NaN,100.0,44.74,4.40,0.16,0.01,0.00,0.00

The index of our dataframe is not good we need to reset it

In [32]:
sewi.reset_index(drop=True, inplace=True)

In [33]:
sewi.columns

Index(['location', 'coordinates.latitude', 'coordinates.longitude', 'unit',
       'co', 'humidity', 'no2', 'o3', 'pm1', 'pm10', 'pm25', 'pressure', 'so2',
       'temperature', 'um003', 'um005', 'um010', 'um025', 'um050', 'um100'],
      dtype='object')

Now save our dataframe to a csv file.

In [34]:
sewi.to_csv('China_Air_Quality.csv', index=False)